platform :ios, '9.3'

use_frameworks!
target 'ErykIosCommon_Tests' do
    pod 'ErykIosCommon', :path => '../'
    pod 'SwiftLint', '~> 0.23.1'
  
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
end
